apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-deployment
spec:
  selector:
    matchLabels:
      app: saleor
  replicas: 1
  template:
    metadata:
      labels:
        app: saleor
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

